#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define ZT_ASCII_PRINTABLE_MIN 0x20
#define ZT_ASCII_PRINTABLE_MAX 0x7e
#define ZT_MICROSECONDS_PER_MILLISECOND 1000
#define ZT_MILLISECONDS_PER_SECOND 1000
#define ZT_PPM_DENOMINATOR 1000000
#define ZT_PROTOCOL_VERSION 1
#define ZT_HTTP_API_VERSION 1
#define ZT_STORE_SCHEMA_VERSION 1
#define ZT_INSTALL_HEADER_SCHEMA 1
#define ZT_FIRMWARE_VERSION "0.2.0"
#define ZT_BUILD_ID_LEN 8
#ifndef ZT_BUILD_ID
#define ZT_BUILD_ID "LIVEG012"
#endif
/* Release tooling supplies exactly eight non-secret printable ASCII bytes. */
typedef enum {
    ZT_OK = 0, ZT_ERR_NOT_IMPLEMENTED, ZT_ERR_INVALID_ARG, ZT_ERR_INVALID_LENGTH,
    ZT_ERR_INVALID_STATE, ZT_ERR_UNSUPPORTED_VERSION, ZT_ERR_AUTH,
    ZT_ERR_NOT_FOUND, ZT_ERR_BUSY, ZT_ERR_NO_SPACE, ZT_ERR_TIMEOUT,
    ZT_ERR_STORAGE, ZT_ERR_RADIO, ZT_ERR_PROTOCOL, ZT_ERR_STALE,
    ZT_ERR_CONFLICT, ZT_ERR_OVERFLOW, ZT_ERR_NETWORK,
    ZT_ERR_HOST_REGISTRATION, ZT_ERR_ROSTER_SIZE, ZT_ERR_ROUND_ACTIVE
} zt_err_t;
#define ZT_ERR_MAX ZT_ERR_ROUND_ACTIVE
#define ZT_MAX_PLAYERS 20
#define ZT_MIN_ROSTER_PLAYERS 2
#define ZT_MAX_LOBBY_DISCOVERIES 8
#define ZT_RX_QUEUE_CAPACITY 32
#define ZT_TX_SLOT_CAPACITY 24
#define ZT_TX_CRITICAL_RESERVE 8
#define ZT_RADIO_SLOT_BYTES 288
#define ZT_EVENT_QUEUE_CAPACITY 32
#define ZT_EVENT_QUEUE_RECORD_BYTES 96
#define ZT_INPUT_QUEUE_CAPACITY 16
#define ZT_TAG_OUTCOME_CAPACITY 16
#define ZT_TAG_OUTBOUND_CAPACITY 1
#define ZT_JOURNAL_CAPACITY 128
#define ZT_JOURNAL_RECORD_MAX_BYTES 96
#define ZT_DEDUPE_CAPACITY 256
#define ZT_DEDUPE_LIFETIME_MS 30000
#define ZT_PENDING_COMMAND_CAPACITY 8
#define ZT_LCD_BUFFER_BYTES 5120
#define ZT_ROUND_DURATION_MS 600000
#define ZT_NAME_MIN_LEN 1
#define ZT_NAME_MAX_LEN 12
#define ZT_NAME_BUFFER_BYTES (ZT_NAME_MAX_LEN + 1)
#define ZT_BEACON_PERIOD_MS 500
#define ZT_BEACON_JITTER_MS 100
#define ZT_RSSI_EWMA_OLD_NUMERATOR 3
#define ZT_RSSI_EWMA_NEW_NUMERATOR 2
#define ZT_RSSI_EWMA_DENOMINATOR 5
#define ZT_RSSI_MIN_SAMPLES 3
#define ZT_RSSI_SAMPLE_WINDOW_MS 1500
#define ZT_TAG_SOURCE_MAX_AGE_MS 1000
#define ZT_PEER_STALE_MS 4000
#define ZT_PEER_EVICT_MS 10000
#define ZT_TAG_RSSI_DEFAULT_DBM (-58)
#define ZT_TIER_IN_RANGE_DBM (-58)
#define ZT_TIER_CLOSE_DBM (-70)
#define ZT_TIER_NEARBY_DBM (-82)
#define ZT_TAG_COOLDOWN_MS 3000
#define ZT_TAG_RETRY_COUNT 3
#define ZT_TAG_RETRY_OFFSETS_MS {0, 250, 750}
#define ZT_TAG_CONFIRM_WAIT_MS 1500
#define ZT_TAG_RESULT_REPEAT_MS 150
#define ZT_TAG_OUTCOME_LIFETIME_MS 10000
#define ZT_PERSIST_PENDING_MS 500
#define ZT_TIME_UNCERTAINTY_MAX_MS 2000
#define ZT_FLOOD_TTL 7
#define ZT_MAX_HOPS 8
#define ZT_FORWARD_JITTER_MIN_MS 30
#define ZT_FORWARD_JITTER_MAX_MS 120
#define ZT_LINK_AGE_ALLOWANCE_MS 3
#define ZT_CLOCK_QUEUE_MAX_MS 200
#define ZT_CLOCK_AGE_MAX_MS 1500
#define ZT_PEER_TIME_RTT_MAX_MS 250
#define ZT_PEER_TIME_MARGIN_MS 10
#define ZT_SERVER_TIME_RTT_MAX_MS 2000
#define ZT_SERVER_TIME_MARGIN_MS 50
#define ZT_CLOCK_DRIFT_PPM 200
#define ZT_CLOCK_LINK_UNCERTAINTY_MS 100
#define ZT_HOST_CLOCK_PERIOD_MS 2000
#define ZT_STATE_PERIOD_MS 10000
#define ZT_STATE_COALESCE_MS 250
#define ZT_COMMAND_RETRY_MS 2000
#define ZT_EVENT_INITIAL_RETRY_COUNT 3
#define ZT_EVENT_INITIAL_RETRY_OFFSETS_MS {0, 700, 1700}
#define ZT_EVENT_RETRY_MS 30000
#define ZT_RETRY_JITTER_PERCENT 20
#define ZT_EVENT_REPLAY_SERVICE_MS 1000
#define ZT_CACHE_CAPACITY 128
#define ZT_RETAINED_ROUND_CAPACITY 2
#define ZT_CACHE_EXCHANGE_CAPACITY 1
#define ZT_CACHE_NEIGHBOR_INTERVAL_MS 10000
#define ZT_CACHE_PAGE_SPACING_MS 200
#define ZT_CACHE_MAX_PAGES 3
#define ZT_OLD_ROUND_INVENTORY_MS 30000
#define ZT_JOIN_RETRY_MS 3000
#define ZT_SNAPSHOT_REQUEST_INTERVAL_MS 5000
#define ZT_ROUND_CLOSE_RETRY_MS 5000
#define ZT_DECISION_RECEIPT_COALESCE_MS 500
#define ZT_START_LEAD_MIN_MS 5000 /* Demo countdown; backend owns the scheduled start. */
#define ZT_ANNOUNCE_MIN_LEN 1
#define ZT_ANNOUNCE_MAX_LEN 96
#define ZT_ANNOUNCE_QUEUE_CAPACITY 3
#define ZT_ANNOUNCE_MAX_DISPLAY_MS 10000
#define ZT_ANNOUNCE_MIN_INTERVAL_MS 15000
#define ZT_GATEWAY_AGE_SATURATION_S 255
#define ZT_GATEWAY_DISCOVERY_MAX_AGE_S 10
#define ZT_STATIC_POOL_MAX_BYTES 65536
#define ZT_TLS_INITIAL_FREE_HEAP_MIN_BYTES 65536
#define ZT_TLS_INITIAL_LARGEST_BLOCK_MIN_BYTES 32768
#define ZT_HOST_MIN_FREE_INTERNAL_HEAP_BYTES 24576
#define ZT_RADIO_REASSEMBLY_MAX_BYTES 2048
#define ZT_TELEMETRY_MAX_NEIGHBORS 4
#define ZT_TELEMETRY_MIN_INTERVAL_MS 10000
#define ZT_TASK_INPUT_PRIORITY 8
#define ZT_TASK_INPUT_STACK_BYTES 3072
#define ZT_TASK_RADIO_PRIORITY 7
#define ZT_TASK_RADIO_STACK_BYTES 6144
#define ZT_TASK_GAME_PRIORITY 6
#define ZT_TASK_GAME_STACK_BYTES 6144
#define ZT_TASK_PERSIST_PRIORITY 5
#define ZT_TASK_PERSIST_STACK_BYTES 4096
#define ZT_TASK_GATEWAY_PRIORITY 4
#define ZT_TASK_GATEWAY_STACK_BYTES 12288
#define ZT_TASK_UI_PRIORITY 3
#define ZT_TASK_UI_STACK_BYTES 4096
#define ZT_TASK_CONSOLE_PRIORITY 2
#define ZT_TASK_CONSOLE_STACK_BYTES 4096
/* Hot paths use caller-owned bounded buffers. Submission APIs copy accepted data
 * before returning; BUSY/NO_SPACE transfers no ownership. No per-frame allocation.
 * Time suffix _us is monotonic microseconds; _ms is milliseconds. */

#ifdef __cplusplus
}
#endif
